name: My First Workflow
on: push
jobs:
    first_job:
        runs-on:  ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My first Github Action job"

        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Get the list of files
          run: |
            ls -al
            pwd
            whoami
            cat /etc/*release*

        - name: Read the Readme.md file
          run: cat README.md
            
        - name: Install cowsay packaage
          run: sudo apt-get install cowsay -y

        - name: Check cowsay is in system path
          run: which cowsay

        - name: Display cowsay message
          run: cowsay -f dragon "Hello I am executing this command using Github Actions" >> dragon.txt

        - name: view the contents of dragon
          run: cat dragon.txt
